version: '3.8'

services:
  
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: rami
      POSTGRES_USER: rami
      POSTGRES_DB: rami
    ports:
    - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
